server:
  port: 8500
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8500/eureka/
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
